# Pull base image.
FROM ubuntu:{UBUNTU_VERSION}

# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential binutils-dev autotools-dev curl git htop man unzip vim wget cmake python python-pip sudo binutils-dev autoconf automake python3 python3-pip && \
  rm -rf /var/lib/apt/lists/*

# for cacheable attestation
RUN python3 -m pip install flask requests
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8


# # Set environment variables.
# ENV HOME /root


RUN useradd -m -u {uid} {username} && usermod -aG sudo {username} && echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

ENV TPM2TOOLS_TCTI tabrmd:bus_name=com.intel.tss2.Tabrmd

ADD start_tpm.sh setup_mock_tpm.sh /usr/local/bin/
ADD setup_tpm_in_docker.sh /
RUN su {username} -c "bash /setup_tpm_in_docker.sh"

USER {username}
WORKDIR /home/{username}

# Define default command.
CMD ["bash"]


